T_base3 =
 
[cos(LegA(0))*cos(LegA(2))*cos(LegA(1) + pi/2) - cos(LegA(0))*sin(LegA(2))*sin(LegA(1) + pi/2), - cos(LegA(0))*cos(LegA(2))*sin(LegA(1) + pi/2) - cos(LegA(0))*cos(LegA(1) + pi/2)*sin(LegA(2)),  sin(LegA(0)), LENGTH_OF_LEGPART*cos(LegA(0))*sin(LegA(2))*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(2))*cos(LegA(1) + pi/2) - (sqrt(3)*TRIANGLE_SIDE)/3]
[cos(LegA(2))*cos(LegA(1) + pi/2)*sin(LegA(0)) - sin(LegA(0))*sin(LegA(2))*sin(LegA(1) + pi/2), - cos(LegA(2))*sin(LegA(0))*sin(LegA(1) + pi/2) - cos(LegA(1) + pi/2)*sin(LegA(0))*sin(LegA(2)), -cos(LegA(0)),                 LENGTH_OF_LEGPART*sin(LegA(0))*sin(LegA(2))*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(2))*cos(LegA(1) + pi/2)*sin(LegA(0)) - LENGTH_OF_LEGPART*cos(LegA(1) + pi/2)*sin(LegA(0))]
[                cos(LegA(2))*sin(LegA(1) + pi/2) + cos(LegA(1) + pi/2)*sin(LegA(2)),                   cos(LegA(2))*cos(LegA(1) + pi/2) - sin(LegA(2))*sin(LegA(1) + pi/2),        0,                                   - LENGTH_OF_LEGPART - LENGTH_OF_LEGPART*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(2))*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(1) + pi/2)*sin(LegA(2))]
[                                                              0,                                                                 0,        0,                                                                                                              1]
 
 
Jv =
 
[LENGTH_OF_LEGPART*cos(LegA(1) + pi/2)*sin(LegA(0)) + LENGTH_OF_LEGPART*cos(LegA(2))*cos(LegA(1) + pi/2)*sin(LegA(0)) - LENGTH_OF_LEGPART*sin(LegA(0))*sin(LegA(2))*sin(LegA(1) + pi/2), LENGTH_OF_LEGPART*cos(LegA(0))*sin(LegA(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(2))*sin(LegA(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(1) + pi/2)*sin(LegA(2)), LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(2))*sin(LegA(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(1) + pi/2)*sin(LegA(2))]
[LENGTH_OF_LEGPART*cos(LegA(0))*sin(LegA(2))*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(2))*cos(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(0))*cos(LegA(1) + pi/2), LENGTH_OF_LEGPART*sin(LegA(0))*sin(LegA(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegA(2))*sin(LegA(0))*sin(LegA(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegA(1) + pi/2)*sin(LegA(0))*sin(LegA(2)), LENGTH_OF_LEGPART*cos(LegA(2))*sin(LegA(0))*sin(LegA(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegA(1) + pi/2)*sin(LegA(0))*sin(LegA(2))]
[                                                                                             0,                         LENGTH_OF_LEGPART*sin(LegA(2))*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(2))*cos(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(1) + pi/2),                 LENGTH_OF_LEGPART*sin(LegA(2))*sin(LegA(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegA(2))*cos(LegA(1) + pi/2)]
 
 
T_base7 =
 
[cos(LegB(1) + pi/2)*sin(LegB(2))*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) - cos(LegB(2))*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2), cos(LegB(2))*cos(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) + sin(LegB(2))*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2), (sqrt(3)*cos(LegB(0)))/2 - sin(LegB(0))/2, LENGTH_OF_LEGPART*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) - (sqrt(3)*TRIANGLE_SIDE)/6 + LENGTH_OF_LEGPART*cos(LegB(2))*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) - LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*sin(LegB(2))*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2)]
[cos(LegB(1) + pi/2)*sin(LegB(2))*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) - cos(LegB(2))*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2), cos(LegB(2))*cos(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) + sin(LegB(2))*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2), cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2,           TRIANGLE_SIDE/2 + LENGTH_OF_LEGPART*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) + LENGTH_OF_LEGPART*cos(LegB(2))*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) - LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*sin(LegB(2))*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2)]
[                                                                    cos(LegB(2))*cos(LegB(1) + pi/2) + sin(LegB(2))*sin(LegB(1) + pi/2),                                                                     cos(LegB(2))*sin(LegB(1) + pi/2) - cos(LegB(1) + pi/2)*sin(LegB(2)),                               0,                                                                                                                 - LENGTH_OF_LEGPART - LENGTH_OF_LEGPART*cos(LegB(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegB(2))*cos(LegB(1) + pi/2) - LENGTH_OF_LEGPART*sin(LegB(2))*sin(LegB(1) + pi/2)]
[                                                                                                                  0,                                                                                                                   0,                               0,                                                                                                                                                                                            1]
 
 
Jv =
 
[LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*sin(LegB(2))*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) - LENGTH_OF_LEGPART*cos(LegB(2))*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) - LENGTH_OF_LEGPART*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2), LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) + LENGTH_OF_LEGPART*cos(LegB(2))*cos(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) + LENGTH_OF_LEGPART*sin(LegB(2))*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2), - LENGTH_OF_LEGPART*cos(LegB(2))*cos(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) - LENGTH_OF_LEGPART*sin(LegB(2))*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2)]
[LENGTH_OF_LEGPART*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) + LENGTH_OF_LEGPART*cos(LegB(2))*sin(LegB(1) + pi/2)*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2) - LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*sin(LegB(2))*(cos(LegB(0))/2 + (sqrt(3)*sin(LegB(0)))/2), LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) + LENGTH_OF_LEGPART*cos(LegB(2))*cos(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) + LENGTH_OF_LEGPART*sin(LegB(2))*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2), - LENGTH_OF_LEGPART*cos(LegB(2))*cos(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2) - LENGTH_OF_LEGPART*sin(LegB(2))*sin(LegB(1) + pi/2)*(sin(LegB(0))/2 - (sqrt(3)*cos(LegB(0)))/2)]
[                                                                                                                                                                           0,                                                                                                       LENGTH_OF_LEGPART*sin(LegB(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegB(2))*sin(LegB(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*sin(LegB(2)),                                                                       LENGTH_OF_LEGPART*cos(LegB(1) + pi/2)*sin(LegB(2)) - LENGTH_OF_LEGPART*cos(LegB(2))*sin(LegB(1) + pi/2)]
 
 
T_base12 =
 
[cos(LegC(1) + pi/2)*sin(LegC(2))*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) - cos(LegC(2))*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2), cos(LegC(2))*cos(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) + sin(LegC(2))*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2), - sin(LegC(0))/2 - (sqrt(3)*cos(LegC(0)))/2, LENGTH_OF_LEGPART*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) - (sqrt(3)*TRIANGLE_SIDE)/6 + LENGTH_OF_LEGPART*cos(LegC(2))*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) - LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*sin(LegC(2))*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2)]
[cos(LegC(1) + pi/2)*sin(LegC(2))*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) - cos(LegC(2))*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2), cos(LegC(2))*cos(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) + sin(LegC(2))*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2),   cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2,           LENGTH_OF_LEGPART*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) - TRIANGLE_SIDE/2 + LENGTH_OF_LEGPART*cos(LegC(2))*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) - LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*sin(LegC(2))*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2)]
[                                                                    cos(LegC(2))*cos(LegC(1) + pi/2) + sin(LegC(2))*sin(LegC(1) + pi/2),                                                                     cos(LegC(2))*sin(LegC(1) + pi/2) - cos(LegC(1) + pi/2)*sin(LegC(2)),                                 0,                                                                                                                 - LENGTH_OF_LEGPART - LENGTH_OF_LEGPART*cos(LegC(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegC(2))*cos(LegC(1) + pi/2) - LENGTH_OF_LEGPART*sin(LegC(2))*sin(LegC(1) + pi/2)]
[                                                                                                                  0,                                                                                                                   0,                                 0,                                                                                                                                                                                            1]
 
 
Jv =
 
[LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*sin(LegC(2))*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) - LENGTH_OF_LEGPART*cos(LegC(2))*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) - LENGTH_OF_LEGPART*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2), LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) + LENGTH_OF_LEGPART*cos(LegC(2))*cos(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) + LENGTH_OF_LEGPART*sin(LegC(2))*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2), - LENGTH_OF_LEGPART*cos(LegC(2))*cos(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) - LENGTH_OF_LEGPART*sin(LegC(2))*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2)]
[LENGTH_OF_LEGPART*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) + LENGTH_OF_LEGPART*cos(LegC(2))*sin(LegC(1) + pi/2)*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2) - LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*sin(LegC(2))*(cos(LegC(0))/2 - (sqrt(3)*sin(LegC(0)))/2), LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) + LENGTH_OF_LEGPART*cos(LegC(2))*cos(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) + LENGTH_OF_LEGPART*sin(LegC(2))*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2), - LENGTH_OF_LEGPART*cos(LegC(2))*cos(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2) - LENGTH_OF_LEGPART*sin(LegC(2))*sin(LegC(1) + pi/2)*(sin(LegC(0))/2 + (sqrt(3)*cos(LegC(0)))/2)]
[                                                                                                                                                                           0,                                                                                                       LENGTH_OF_LEGPART*sin(LegC(1) + pi/2) + LENGTH_OF_LEGPART*cos(LegC(2))*sin(LegC(1) + pi/2) - LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*sin(LegC(2)),                                                                       LENGTH_OF_LEGPART*cos(LegC(1) + pi/2)*sin(LegC(2)) - LENGTH_OF_LEGPART*cos(LegC(2))*sin(LegC(1) + pi/2)]
 